services:
  - type: web
    name: food-delivery-spring
    runtime: java
    buildCommand: mvn clean install
    startCommand: java -jar target/dishdashapi-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 21